service: c7p-classify
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-dotenv-plugin
custom:
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  accountid: ${env:AWS_ACCOUNT_ID}
  processingbucket: ${env:CHAPTER7_PIPELINE_PROCESSING_BUCKET}
  dotenv:
    path: ../.env

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: Allow
      Action:
        - comprehend:DetectSentiment
        - comprehend:StartDocumentClassificationJob
        - comprehend:DescribeDocumentClassificationJob
        - comprehend:classifyDocument
      Resource: "*"
    - Effect: Allow
      Action:
        - sts:AssumeRole
      Resource:
        - ${env:CHAPTER7_DATA_ACCESS_ARN}
    - Effect: Allow
      Action:
        - iam:PassRole
      Resource: "*"

resources:
  Resources:
    ProcessingBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.processingbucket}
        AccessControl: Private

functions:
  classify:
    handler: handler.classify
    events:
      - stream:
          type: kinesis
          arn: ${env:CHAPTER7_PIPELINE_CLASSIFY_STREAM_ARN}
          batchSize: 100
          startingPosition: LATEST
          enabled: true
          async: true
