service: c7p-sentiment
frameworkVersion: ">=1.30.0"
plugins:
  - serverless-dotenv-plugin
custom:
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  accountid: ${env:AWS_ACCOUNT_ID}
  dotenv:
    path: ../.env

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${env:AWS_DEFAULT_REGION, 'eu-west-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - comprehend:DetectSentiment
      Resource: "*"
    - Effect: Allow
      Action:
        - kinesis:PutRecord
        - kinesis:PutRecords
      Resource: "*"

resources:
  Resources:
    KinesisStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${env:CHAPTER7_PIPELINE_CLASSIFY_STREAM}
        ShardCount: ${env:CHAPTER7_PIPELINE_SHARD_COUNT}

functions:
  detect:
    handler: handler.detect
    events:
      - stream:
          type: kinesis
          arn: ${env:CHAPTER7_PIPELINE_SENTIMENT_STREAM_ARN}
          batchSize: 100
          startingPosition: LATEST
          enabled: true
          async: true

